parameters:
    bcmath.scale: 4
    base.currency: EUR
    deposit.business.fee: 0.03
    deposit.private.fee: 0.03
    withdraw.business.fee: 0.5
    withdraw.private.fee: 0.3
    withdraw.private.free.amount.per.week: 1000
    withdraw.private.free.count.per.week: 3
    rate.api.url: https://api.exchangeratesapi.io/latest

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{Model,Kernel.php}'

    App\Command\PrintCommissionCommand:
        $baseCurrency: '%base.currency%'

    App\DataProvider\RateDataProvider:
        class: App\DataProvider\RateDataProvider
        arguments:
            $url: '%rate.api.url%'

    deposit.business.strategy:
        class: App\Commission\FixedFeeStrategy
        arguments:
            $fee: '%deposit.business.fee%'
            $scale: '%bcmath.scale%'

    deposit.private.strategy:
        class: App\Commission\FixedFeeStrategy
        arguments:
            $fee: '%deposit.private.fee%'
            $scale: '%bcmath.scale%'

    withdraw.business.strategy:
        class: App\Commission\FixedFeeStrategy
        arguments:
            $fee: '%withdraw.business.fee%'
            $scale: '%bcmath.scale%'

    App\Commission\RangeStrategy:
        class: App\Commission\RangeStrategy

    App\Commission\WeeklyRange:
        class: App\Commission\WeeklyRange

    App\DataProvider\TransactionDataProvider:
        class: App\DataProvider\TransactionDataProvider
        arguments:
            $scale: '%bcmath.scale%'

    withdraw.private.strategy:
        class: App\Commission\RangeStrategy
        arguments:
            $rangeCalculator: '@App\Commission\WeeklyRange'
            $dataProvider: '@App\DataProvider\TransactionDataProvider'
            $fee: '%withdraw.private.fee%'
            $freeAmountPerWeek: '%withdraw.private.free.amount.per.week%'
            $freeWithdrawCountPerWeek: '%withdraw.private.free.count.per.week%'
            $scale: '%bcmath.scale%'

    App\Service\CommissionCalculator:
        class: App\Service\CommissionCalculator
        arguments:
            $depositPrivateStrategy: '@deposit.private.strategy'
            $depositBusinessStrategy: '@deposit.business.strategy'
            $withdrawPrivateStrategy: '@withdraw.private.strategy'
            $withdrawBusinessStrategy: '@withdraw.business.strategy'

    App\Formatter\Formatter:
        class: App\Formatter\Formatter
