parameters:
    bcmath.scale: 4
    base.currency: EUR
    deposit.business.fee: '0.03'
    deposit.private.fee: '0.03'
    withdraw.business.fee: '0.5'
    withdraw.private.fee: '0.3'
    withdraw.private.free.amount.per.week: '1000'
    withdraw.private.free.count.per.week: '3'
    rate.api.url: https://api.exchangeratesapi.io/latest

services:
    _defaults:
        autowire: true
        autoconfigure: true

        bind:
            $bcmathScale: '%bcmath.scale%'
            $baseCurrency: '%base.currency%'

    _instanceof:
        App\Commission\CommissionInterface:
            tags: ['app.commission_strategy']
        App\Iterator\FileStrategyInterface:
            tags: ['app.file_strategy']

    App\:
        resource: '../src/*'
        exclude: '../src/{Model,Kernel.php}'

    App\Commission\StrategyContext:
        class: App\Commission\StrategyContext
        arguments:
            - !tagged_iterator app.commission_strategy

    App\Iterator\FileContext:
        class: App\Iterator\FileContext
        arguments:
            - !tagged_iterator app.file_strategy

    App\DataProvider\RateDataProvider:
        class: App\DataProvider\RateDataProvider
        arguments:
            $url: '%rate.api.url%'

    App\Service\CommissionCalculator:
        class: App\Service\CommissionCalculator
        arguments:
            $data:
                depositPrivate:
                    strategy: App\Commission\FixedFeeStrategy
                    fee: '%deposit.private.fee%'
                depositBusiness:
                    strategy: App\Commission\FixedFeeStrategy
                    fee: '%deposit.business.fee%'
                withdrawPrivate:
                    strategy: App\Commission\RangeStrategy
                    fee: '%withdraw.private.fee%'
                    freeAmountPerWeek: '%withdraw.private.free.amount.per.week%'
                    freeWithdrawCountPerWeek: '%withdraw.private.free.count.per.week%'
                withdrawBusiness:
                    strategy: App\Commission\FixedFeeStrategy
                    fee: '%withdraw.business.fee%'
